# Generated by Django 5.1.3 on 2024-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_media')),
                ('activePerDay', models.IntegerField(default=0)),
            ],
        ),
    ]
